# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employ',
            new_name='user',
        ),
    ]
