# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170316_0708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Person',
        ),
    ]
